### ISSUE TITLE
Hang on main() return

### ISSUE THREAD

**Issue by Alarm-Siren** [peternoyes/dodo#5]
If for some reason your Dodo program returns from main(), the Dodo console itself hangs with no error. Only a reset or power cycle will restore it to working order. I would suggest that in these circumstances, the system ought to return to the main Dodo splash screen.

**Comment by peternoyes** [comment]
The proposed fix addresses the issue in the core system firmware. Additionally games will need to be recompiled in the playground in order to properly return. A fix in the playground will accompany this fix. This will be the first change toward version 1.1.0 system firmware.
